Repository yearn/ydaemon, pull requests merged in 2022-09, with the labels that each got.

#24 feat: add new strategies
  data/meta/strategies/1/AaveLenderOptimizer.json
  data/meta/strategies/1/BalancerReinvest.json
  data/meta/strategies/1/IdleReinvest.json
  data/meta/strategies/1/IronbankLenderOptimizer.json
  data/meta/strategies/10/AaveIronbankLenderOptimizer.json
  data/meta/strategies/10/to_remove_once_populated.json
  data/meta/tokens/1/0x7B50775383d3D6f0215A8F290f2C9e2eEBBEceb2.json
Labels: enhancement

#31 feat: add partners routes
  cmd/main.go
  data/partners/networks/1/akropolis.json
  data/partners/networks/1/ambire.json
  data/partners/networks/1/basketdao.json
  data/partners/networks/1/element.json
  data/partners/networks/1/gb.json
  data/partners/networks/1/popcorndao.json
  data/partners/networks/1/rhinofi.json
  data/partners/networks/1/shapeshiftdao.json
  data/partners/networks/1/wido.json
  data/partners/networks/1/yapeswap.json
  data/partners/networks/1/yieldster.json
  data/partners/networks/250/beethovenx.json
  data/partners/networks/250/wido.json
  internal/controllers/route.helpers.go
  internal/controllers/route.partners.all.go
  internal/controllers/server.go
  internal/controllers/server_test.go
  internal/daemons/meta.api.protocols.go
  internal/daemons/meta.api.strategies.go
  internal/daemons/meta.api.tokens.go
  internal/daemons/meta.api.vaults.go
  internal/daemons/partners.api.all.go
  internal/daemons/summonner.go
  internal/models/store.go
  internal/store/store.go
  internal/utils/constants.go
Labels: enhancement

#47 feat(risk): add bb-a-usd aura auto staker group
  data/risks/networks/1/bb-a-usdauraautostaker.json
Labels: risk framework

#58 feat(meta): update strategies & protocols
  data/meta/protocols/1/AuraFinance.json
  data/meta/strategies/1/AuraReinvest.json
  data/meta/strategies/1/IdleReinvest.json
Labels: enhancement, meta

#57 feat(risk): Change testingScore from 3 -> 2
  data/risks/networks/1/maker-lev.json
Labels: risk framework

#65 feat: update blacklist vaults and add reason
  internal/utils/helpers/constants.go
Labels: enhancement

#66 feat(risk): add allocation median score api - refactor proposal
  internal/strategies/daemon.strategies.risk.go
  internal/utils/helpers/helpers.go
Labels: enhancement

#70 fix: checksumAddress lowercase in json
  internal/meta/daemon.strategies.files.go
  internal/meta/daemon.tokens.files.go
  internal/meta/daemon.vaults.files.go
  internal/meta/models.go
  internal/meta/store.go
  internal/partners/daemon.partners.files.go
  internal/partners/models.go
  internal/partners/prepare.balances.go
  internal/partners/route.partners.all.go
  internal/partners/route.partners.one.go
  internal/partners/store.go
  internal/prices/daemon.prices.multicall.go
  internal/prices/daemon.prices.multicall.test.go
  internal/prices/route.prices.all.go
  internal/prices/route.prices.some.go
  internal/prices/store.go
  internal/strategies/daemon.strategies.graph.go
  internal/strategies/daemon.strategies.multicall.go
  internal/strategies/daemon.strategies.risk.go
  internal/strategies/daemon.withdrawalQueue.multicall.go
  internal/strategies/models.go
  internal/strategies/models.risk.go
  internal/strategies/prepare.strategies.go
  internal/strategies/store.go
  internal/tokens/daemon.tokens.graph.go
  internal/tokens/model.go
  internal/tokens/route.tokens.all.go
  internal/tokens/store.go
  internal/types/bigNumber/float.go
  internal/types/bigNumber/int.go
  internal/types/common/address.go
  internal/utils/ethereum/multicall.go
  internal/utils/ethereum/utils.go
  internal/utils/helpers/constants.go
  internal/utils/helpers/helpers.go
  internal/utils/helpers/helpers_test.go
  internal/utils/models/graph.go
  internal/utils/models/store.go
  internal/vaults/daemon.vaults.multicall.go
  internal/vaults/daemon.vaults.v1.go
  internal/vaults/models.go
  internal/vaults/prepare.tvl.go
  internal/vaults/prepare.vaults.go
  internal/vaults/store.go
Labels: bug
